package com.bibliotheques.appliweb.consumer.generated.editionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.bibliotheques.appliweb.model.bean.edition.Edition;
import com.bibliotheques.appliweb.model.bean.edition.Exemplaire;
import com.bibliotheques.appliweb.model.exception.GetListExemplaireFault_Exception;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-10T10:06:10.596+02:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/EditionService/", name = "EditionService")
@XmlSeeAlso({ObjectFactory.class, com.bibliotheques.appliweb.model.bean.objectfactory.ObjectFactory.class})
public interface EditionService {

    @WebMethod
    @RequestWrapper(localName = "getListEdition", targetNamespace = "http://www.example.org/EditionService/", className = "org.example.editionservice.GetListEdition")
    @ResponseWrapper(localName = "getListEditionResponse", targetNamespace = "http://www.example.org/EditionService/", className = "org.example.editionservice.GetListEditionResponse")
    @WebResult(name = "edition", targetNamespace = "")
    public java.util.List<Edition> getListEdition(
        @WebParam(name = "nbEdition", targetNamespace = "")
        int nbEdition
    );

    @WebMethod
    @RequestWrapper(localName = "getListExemplaire", targetNamespace = "http://www.example.org/EditionService/", className = "org.example.editionservice.GetListExemplaire")
    @ResponseWrapper(localName = "getListExemplaireResponse", targetNamespace = "http://www.example.org/EditionService/", className = "org.example.editionservice.GetListExemplaireResponse")
    @WebResult(name = "exemplaire", targetNamespace = "")
    public java.util.List<Exemplaire> getListExemplaire(
        @WebParam(name = "editionId", targetNamespace = "")
        int editionId
    ) throws GetListExemplaireFault_Exception;
}
